name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        uses: ./.github/workflows/run-tests-workflow.yml
        with:
          node-version: 18
        secrets:
          jwt_secret: ${{ secrets.JWT_SECRET }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package for Lambda
        run: |
          mkdir deploy-package
          cp -r dist deploy-package
          cp -r node_modules deploy-package
          cd deploy-package
          zip -r ../lambda-package.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.6
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: WhatGrowsServer
          zip_file: lambda-package.zip
