name: Run Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  test-and-lint:
    uses: ./.github/workflows/run-tests-workflow.yml@main
    with:
      node-version: 18
    secrets:
      jwt_secret: ${{ secrets.JWT_SECRET }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
